import type { Metadata } from "next";
import "../../styles/globals.css";
import { Navbar } from "@repo/ui/navbar";
import "@repo/ui/styles.css";
import DailyDiscoveriesIcon from "../../public/daily_discoveries_icon.png";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <Navbar icon={DailyDiscoveriesIcon} session={session} />
        {children}
      </body>
    </html>
  );
}
