import type { Metadata } from "next";
import "../../styles/globals.css";
import { Navbar } from "@repo/ui/navbar";
import SessionWrapper from "@repo/ui/session-wrapper";
import "@repo/ui/styles.css";
import DailyDiscoveriesIcon from "../../public/daily_discoveries_icon.png";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log('Fetching session...');
  const session = await getServerSession(authOptions);
  console.log('Session:', session); // Debugging line

  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <div>TEST {JSON.stringify(session)}</div>
          <Navbar icon={DailyDiscoveriesIcon} session={session} />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
